name: voip_app
description: Um cliente VoIP móvel minimal em Flutter (exemplo)
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_webrtc: ^0.12.12+hotfix.1
  sip_ua: ^1.0.1
  provider: ^6.1.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
